/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Business testaurant = new Business("The Java Diner","$", "restaurant");
        Business.addReview("I hated this diner","PythonFan123",0,testaurant);
        Business.addReview("Try the linked lists!","NoMoreArrays",4,testaurant);
        Business.addReview("Java is great!","A. Developer",5,testaurant);

        System.out.println(Business.toBusinessString(testaurant));
    }
}
