/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Restaurant testaurant = new Restaurant("The Java Diner","$");
        Restaurant.addReview("I hated this diner","PythonFan123",0,testaurant);
        Restaurant.addReview("Try the linked lists!","NoMoreArrays",4,testaurant);
        Restaurant.addReview("Java is great!","A. Developer",5,testaurant);

        System.out.println(Restaurant.toRestString(testaurant));
    }
}
