/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {


    @Test void testRestaurantConstructor() {
        Restaurant testaurant = new Restaurant("The Java Diner","$","", "restaurant");
        assertEquals("The Java Diner",testaurant.getName());
        assertEquals("restaurant",testaurant.getBusinessType());
    }

    @Test void testToRestStringNoReviews() {
        Restaurant testaurant = new Restaurant("The Java Diner","$","", "restaurant");
        assertEquals("The Java Diner: 0 stars, $",Restaurant.toRestaurantString(testaurant));
    }

    @Test void testToRestStringWithReviews() {
        Restaurant testaurant = new Restaurant("The Java Diner","$","", "restaurant");
        Business.addReview("I hated this diner","PythonFan123",0,testaurant);
        Business.addReview("Try the linked lists!","NoMoreArrays",4,testaurant);
        Business.addReview("Java is great!","A. Developer",5,testaurant);

        assertEquals("The Java Diner: 3 stars, $\nI hated this diner | 0 stars. -PythonFan123\nTry the linked lists! | 4 stars. -NoMoreArrays\nJava is great! | 5 stars. -A. Developer",Restaurant.toRestaurantString(testaurant));
        assertEquals(3,testaurant.getAverageRating());
    }

    @Test void testReviewConstructor() {
        Restaurant testaurant = new Restaurant("The Java Diner","$","", "restaurant");
        Review testReview1 = new Review("Java is great!","A. Developer",5,testaurant);
        Review testReview2 = new Review("Try the linked lists!","NoMoreArrays",4,testaurant);
        Review testReview3 = new Review("I hated this diner","PythonFan123",0,testaurant);

        assertEquals("Java is great!", testReview1.getBody());
        assertEquals("NoMoreArrays", testReview2.getAuthor());
        assertEquals(0, testReview3.getRating());
    }

    @Test void testReviewString() {
        Restaurant testaurant = new Restaurant("The Java Diner","$","", "restaurant");
        Review testReview1 = new Review("Java is great!","A. Developer",5,testaurant);

        assertEquals(Review.toReviewString(testReview1),"Java is great! | 5 stars. -A. Developer");
    }

    @Test void testAddReview() {
        Restaurant testaurant = new Restaurant("The Java Diner","$","", "restaurant");

        Business.addReview("Java is great!","A. Developer",5,testaurant);

        assertNotNull(testaurant.getReviewsList());
    }

}
