/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    Restaurant testaurant = new Restaurant("The Java Diner",0,"$",null);

    @Test void testRestaurantConstructor() {
        assertEquals(testaurant.name,"The Java Diner");
        assertNull(testaurant.reviewsList);
    }

    @Test void testToRestString() {
        assertEquals(Restaurant.toRestString(testaurant),"");
    }

    @Test void testReviewConstructor() {
        Review testReview1 = new Review("Java is great!","A. Developer",5,testaurant);
        Review testReview2 = new Review("Try the linked lists!","NoMoreArrays",4,testaurant);
        Review testReview3 = new Review("I hated this diner","PythonFan123",0,testaurant);

        assertEquals(testReview1.body,"Java is great!");
        assertEquals(testReview2.author,"NoMoreArrays");
        assertEquals(testReview3.rating,0);
        assertEquals(testReview1.restaurant.name,"The Java Cafe");
    }

    @Test void testReviewString() {
        Review testReview1 = new Review("Java is great!","A. Developer",5,testaurant);
        assertEquals(Review.toReviewString(testReview1),"Java is great! | 5 stars. -A. Developer");
    }

    @Test void testAddReview() {
        Restaurant.addReview("Java is great!","A. Developer",5,testaurant);
        assertNotNull(testaurant.reviewsList);
    }
}
