/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
// errors at line 64 (oneError, fewErrors); 26, 73, 84 (fewErrors)
    @Test void testLintSemicolonsNoErrors() throws IOException {
        String testFileNoErrors = "noErrors";
        String expectedResult = "noErrors";

        assertEquals(expectedResult,App.lintSemicolons(testFileNoErrors));
    }

    @Test void testLintSemicolonsOneError() throws IOException {
        String testFileOneError = "oneError";
        String expectedResult = "oneError\n" +
                "Line 64: missing semicolon";

        assertEquals(expectedResult,App.lintSemicolons(testFileOneError));
        }


    @Test void testLintSemicolonsFewErrors() throws IOException {
        String testFileFewErrors = "fewErrors";
        String expectedResult = "fewErrors\n" +
                "Line 26: missing semicolon\n" +
                "Line 32: missing semicolon\n" +
                "Line 49: missing semicolon\n" +
                "Line 64: missing semicolon";

        assertEquals(expectedResult,App.lintSemicolons(testFileFewErrors));
    }

    @Test void testLintSemicolonsManyErrors() throws IOException {
        String testFileManyErrors = "manyErrors";
        String expectedResult = "manyErrors\n" +
                "Line 3: missing semicolon\n" +
                "Line 11: missing semicolon\n" +
                "Line 13: missing semicolon\n" +
                "Line 15: missing semicolon\n" +
                "Line 20: missing semicolon\n" +
                "Line 21: missing semicolon\n" +
                "Line 26: missing semicolon\n" +
                "Line 28: missing semicolon\n" +
                "Line 32: missing semicolon\n" +
                "Line 36: missing semicolon\n" +
                "Line 40: missing semicolon\n" +
                "Line 47: missing semicolon\n" +
                "Line 49: missing semicolon\n" +
                "Line 50: missing semicolon\n" +
                "Line 51: missing semicolon\n" +
                "Line 53: missing semicolon\n" +
                "Line 55: missing semicolon\n" +
                "Line 64: missing semicolon\n" +
                "Line 65: missing semicolon";

        assertEquals(expectedResult,App.lintSemicolons(testFileManyErrors));
    }
}
